sudo: required
language: generic

cache:
  directories:
  - $HOME/google-cloud-sdk

services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1


before_install:
- sudo apt-get install python3.10
- export CLOUDSDK_PYTHON=/usr/bin/python3
- rm -rf $HOME/google-cloud-sdk;

- curl https://sdk.cloud.google.com | bash > /dev/null;
  
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud version


 
  
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file  service-account.json
  - gcloud config  set project   multi-k8s-406506
  - gcloud config set compute/zone europe-west2
  - gcloud container clusters get-credentials  autopilot-cluster-1 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker build -t khaledkhaled/react-test -f ./client/Dockerfile.dev ./client
install: true
script:
  - docker run -e CI=true khaledkhaled/react-test npm test -- --coverage
  

 

  # Log in to the docker CLI

  # Take those images and push them to docker hub


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY


  # app: 'multi-docker'
  # env: 'MultiDocker-env'
  # bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  # bucket_path: 'docker-multi'